"""add blacklist table

Revision ID: 09d787882cca
Revises: 21d6bddc1385
Create Date: 2021-02-28 22:06:05.431662

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "09d787882cca"
down_revision = "21d6bddc1385"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklist_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("blacklisted_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
        schema="spotify_playlists",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user", schema="spotify_playlists")
    op.drop_table("spotify_playlists", schema="spotify_playlists")
    op.drop_table("blacklist_tokens", schema="spotify_playlists")
    # ### end Alembic commands ###
