"""db changed column to unique

Revision ID: 36250c148393
Revises: a5bab65a45a2
Create Date: 2021-03-04 19:10:23.135866

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "36250c148393"
down_revision = "a5bab65a45a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "playlist", ["playlist_link"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "playlist", type_="unique")
    # ### end Alembic commands ###
