"""added relationship between playlist and user

Revision ID: 8ba1e8335ee1
Revises: 36250c148393
Create Date: 2021-03-05 22:15:47.833127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ba1e8335ee1"
down_revision = "36250c148393"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("playlist", sa.Column("created_by", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "playlist", "users", ["created_by"], ["user_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "playlist", type_="foreignkey")
    op.drop_column("playlist", "created_by")
    # ### end Alembic commands ###
