"""db init

Revision ID: a5bab65a45a2
Revises: Create Date: 2021-03-04 11:25:43.734874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a5bab65a45a2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklist_token",
        sa.Column("token_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("blacklisted_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("token_id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "playlist",
        sa.Column("playlist_id", sa.String(length=100), nullable=False),
        sa.Column("datasource", sa.String(), nullable=False),
        sa.Column("screen_name", sa.String(), nullable=False),
        sa.Column("playlist_link", sa.String(), nullable=False),
        sa.Column("playlist_description", sa.Text(), nullable=True),
        sa.Column("last_update", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("playlist_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("registered_on", sa.DateTime(), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=False),
        sa.Column("public_id", sa.String(length=100), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("password_hash", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("playlist")
    op.drop_table("blacklist_token")
    # ### end Alembic commands ###
